baseurl = "/"
languageCode = "es"
defaultContentLanguage = "en"
title = "La Cocina de Estercita"
theme = "hugo-theme-dream"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Norma 'Estercita' Ortega"
  # description = ""
  avatar = "/img/avatar.jpg"
  motto = "A comer!"
  
  email = "elenavilchezo@gmail.com"
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2020

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404Button = true
